// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/johnwtracy/personal/src/apiserver/internal/ent/blogpost"
)

// BlogPost is the model entity for the BlogPost schema.
type BlogPost struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Head holds the value of the "head" field.
	Head string `json:"head,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BlogPostQuery when eager-loading is set.
	Edges BlogPostEdges `json:"edges"`
}

// BlogPostEdges holds the relations/edges for other nodes in the graph.
type BlogPostEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*Topic
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e BlogPostEdges) TagsOrErr() ([]*Topic, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BlogPost) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // head
		&sql.NullString{}, // body
		&sql.NullTime{},   // create_time
		&sql.NullTime{},   // update_time
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BlogPost fields.
func (bp *BlogPost) assignValues(values ...interface{}) error {
	if m, n := len(values), len(blogpost.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	bp.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field head", values[0])
	} else if value.Valid {
		bp.Head = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field body", values[1])
	} else if value.Valid {
		bp.Body = value.String
	}
	if value, ok := values[2].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field create_time", values[2])
	} else if value.Valid {
		bp.CreateTime = value.Time
	}
	if value, ok := values[3].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field update_time", values[3])
	} else if value.Valid {
		bp.UpdateTime = value.Time
	}
	return nil
}

// QueryTags queries the tags edge of the BlogPost.
func (bp *BlogPost) QueryTags() *TopicQuery {
	return (&BlogPostClient{config: bp.config}).QueryTags(bp)
}

// Update returns a builder for updating this BlogPost.
// Note that, you need to call BlogPost.Unwrap() before calling this method, if this BlogPost
// was returned from a transaction, and the transaction was committed or rolled back.
func (bp *BlogPost) Update() *BlogPostUpdateOne {
	return (&BlogPostClient{config: bp.config}).UpdateOne(bp)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (bp *BlogPost) Unwrap() *BlogPost {
	tx, ok := bp.config.driver.(*txDriver)
	if !ok {
		panic("ent: BlogPost is not a transactional entity")
	}
	bp.config.driver = tx.drv
	return bp
}

// String implements the fmt.Stringer.
func (bp *BlogPost) String() string {
	var builder strings.Builder
	builder.WriteString("BlogPost(")
	builder.WriteString(fmt.Sprintf("id=%v", bp.ID))
	builder.WriteString(", head=")
	builder.WriteString(bp.Head)
	builder.WriteString(", body=")
	builder.WriteString(bp.Body)
	builder.WriteString(", create_time=")
	builder.WriteString(bp.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(bp.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BlogPosts is a parsable slice of BlogPost.
type BlogPosts []*BlogPost

func (bp BlogPosts) config(cfg config) {
	for _i := range bp {
		bp[_i].config = cfg
	}
}
