// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// BlogPost is the predicate function for blogpost builders.
type BlogPost func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)
